version: "3"
services:
  mqtt-broker:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: mqtt-broker
    restart: unless-stopped
    user: 1883:1883
    volumes:
    volumes:
      - ./mosquitto/conf:/mosquitto/conf
      - ./mosquitto/log:/mosquitto/log
      - ./certbot/conf:/etc/letsencrypt
      - ./scripts:/scripts
      - ./mosquitto/data:/mosquitto/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 1883:1883
      - 8083:8083
      - 8883:8883
    environment:
      - DOMAIN=YOUR_DOMAIN_HERE
      - EMAIL=YOUR_DOMAIN_EMAIL
      - PUID=1883
      - PGID=1883

  certbot:
     image: certbot/certbot:latest
     command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email YOUR_DOMAIN_EMAIL --agree-tos --no-eff-email -d YOUR_DOMAIN_HERE
     volumes:
       - ./certbot/conf/:/etc/letsencrypt
       - ./certbot/logs/:/var/log/letsencrypt
       - ./certbot/data:/usr/share/nginx/html/letsencrypt
    ports:
       - 8116:80
