version: "3"
services:
  mqtt-broker:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: mqtt-broker
    restart: unless-stopped
    user: 1883:1883
    volumes:
    volumes:
      - ./mosquitto/conf:/mosquitto/conf
      - ./mosquitto/log:/mosquitto/log
      - ./letsencrypt:/etc/letsencrypt
      - ./scripts:/scripts
      - ./mosquitto/data:/mosquitto/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 1883:1883
      - 8083:8083
      - 8883:8883
      - 8116:80
    environment:
      - DOMAIN=YOUR_DOMAIN_HERE
      - EMAIL=YOUR_DOMAIN_EMAIL
    environment:
      - PUID=1883
      - PGID=1883
