version: "3"
services:
  mqtt-broker:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: mqtt-broker
    restart: unless-stopped
    user: 1883:1883
    volumes:
      - ./mosquitto/conf:/mosquitto/conf
      - ./mosquitto/log:/mosquitto/log
      - ./letsencrypt/chain.pem:/etc/letsencrypt/chain.pem
      - YOUR_CERT_PATH:/etc/letsencrypt/certificates:ro
      - ./scripts:/scripts
      - ./mosquitto/data:/mosquitto/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 1883:1883
      - 8083:8083
      - 8883:8883
    environment:
      - PUID=1883
      - PGID=1883
